### ISSUE TITLE
 No module named dotenv

### ISSUE THREAD

**Issue by andreknieriem** [algolia/docsearch-scraper#317]
Hey, I get the error above if I am running docsearch. Of course I run pip install requirements.txt but this doesn't seem to work very well. 

I am on a 14.04 Ubuntu with python und python-pip installed.  Maybe someone can help me.

**Comment by andreknieriem** [comment]
Hey, my "mistake". The pip install fails because I was missing some packages.

**Comment by redox** [comment]
> Hey, my "mistake". The pip install fails because I was missing some packages.

No worries, let us know how that goes :)
