### ISSUE TITLE
ImportError: No module named scrapy.linkextractors.lxmlhtml

### ISSUE THREAD

**Issue by umeshkalia** [algolia/docsearch-scraper#320]
While executing following command 
./docsearch
I am getting following error
ImportError: No module named scrapy.linkextractors.lxmlhtml

I am using Python 2.7.6 at Centos 6,8.
Here are modules installed listed by command pip list
algoliasearch (1.9.2)
attrs (16.2.0)
cffi (1.8.3)
click (6.6)
cryptography (1.5)
cssselect (0.9.2)
dotenv (0.0.5)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.17)
lxml (3.6.4)
paramiko (2.0.2)
parsel (1.0.3)
pip (8.1.2)
psutil (4.3.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
PyDispatcher (2.0.5)
pyOpenSSL (16.1.0)
python-dotenv (0.6.0)
queuelib (1.4.2)
requests (2.11.1)
Scrapy (1.1.2)
service-identity (16.0.0)
setuptools (27.3.0)
six (1.10.0)
Twisted (16.4.1)
w3lib (1.15.0)
wheel (0.29.0)
zope.interface (4.3.2)

Please advise solution asap.

**Comment by maxiloc** [comment]
@umeshkalia Sorry for the delay.

We made some changes to imports.

Can you pull the master branch and try running:

```
pip install -r requirement.txt
./docsearch
```

And tell us how it goes ?

Thanks

**Comment by maxiloc** [comment]
Closing this. Feel free to reopen if needed

**Comment by kamrankausar** [comment]
ImportError: No module named linkextractor
(scrapy_py27_env) kamran@DL1XTEC001:~/scrapy_xerago/scrapy_env/imagecrawler$ 
Package          Version    
---------------- -----------
attrs            19.3.0     
Automat          0.8.0      
cffi             1.13.2     
constantly       15.1.0     
cryptography     2.8        
cssselect        1.1.0      
enum34           1.1.6      
functools32      3.2.3.post2
hyperlink        19.0.0     
idna             2.8        
incremental      17.5.0     
ipaddress        1.0.23     
lxml             4.4.2      
parsel           1.5.2      
pip              20.0.1     
Protego          0.1.16     
pyasn1           0.4.8      
pyasn1-modules   0.2.8      
pycparser        2.19       
PyDispatcher     2.0.5      
PyHamcrest       1.10.1     
pyOpenSSL        19.1.0     
queuelib         1.5.0      
Scrapy           1.8.0      
service-identity 18.1.0     
setuptools       44.0.0     
six              1.14.0     
Twisted          19.10.0    
w3lib            1.21.0     
wheel            0.33.6     
zope.interface   4.7.1
