### ISSUE TITLE
CI that runs on PRs of configs

### ISSUE THREAD

**Issue by Haroenv** [algolia/docsearch-scraper#338]
If it's an existing config, run that one and suggest to update the `nbHits` in a comment. You could use [Danger](http://danger.systems) for this, since it's an easy way to run some things and comment on GitHub. 

Another thing that could be checked is whether it's valid JSON, and if it's a valid docsearch config (by checking if necessary keys are present, and if they have the right values), this is related to #326

**Comment by Haroenv** [comment]
tracked in https://github.com/algolia/docsearch-scraper/issues/338

**Comment by lottec** [comment]
Hey, is this likely to be picked up soon?

Currently looking at running the scraper on own infra, adding to our CI pipeline, but if this was likely to be added to the Docsearch offering that'd be amazing...!

**Comment by Haroenv** [comment]
This isn't done yet, but feel free to open a PR @lottec !

**Comment by s-pace** [comment]
Issue addressed thanks to this PR:
https://github.com/algolia/docsearch-configs/pull/2059
