### ISSUE TITLE
AttributeError: 'ConfigLoader' object has no attribute 'nb_hits_max'

### ISSUE THREAD

**Issue by majolo** [algolia/docsearch-scraper#367]
We're running into this bug when running the scraper, would be nice to get a fix as soon as possible.

The offending line (29 in scraper/src/index.py) seems to have been introduced in the last commit.

**Comment by majolo** [comment]
@s-pace

**Comment by s-pace** [comment]
👋 @majolo ,

Just a quick message to let you know that we use this parameter in our environment variables.

You can set a super huge value if you want to avoid any issue.

We keep in mind this issue. We will fix it soone
