### ISSUE TITLE
trivial spelling error  s/scrapper/scraper/g

### ISSUE THREAD

**Issue by jmarca** [algolia/docsearch-scraper#398]
Sorry if this is an annoyance, but...just noticed that the docker build script creates "...scrapper" not "...scraper"

```
$ grep "docker build" * -R
cli/scripts/publish_docker_scraper_images.sh:docker build -t algolia/base-documentation-scrapper -f scraper/dev/docker/Dockerfile.base .
cli/scripts/publish_docker_scraper_images.sh:docker build -t algolia/documentation-scrapper -f scraper/dev/docker/Dockerfile .
```

Of course, changing this so that the build images are "algolia/documentation-scraper" might break lots of things.

**Comment by s-pace** [comment]
👋 @jmarca 

Thank you for reporting. We are aware of this typo and we will remove it in the next development.
