### ISSUE TITLE
DocSearch is not capable to run Firefox when the "js_render" option is set

### ISSUE THREAD

**Issue by fmarinitrs** [algolia/docsearch-scraper#399]
When we want to scrap a page after the Javascript is run (with the js_render option on the Algolia index config file) and DocSearch is running on a server without GUI, a Firefox window is attempted to be opened but an exception is raised due to that's not doable in that environment.
Solution: Running Firefox on headless mode (and, separately, installing a geckodriver).
Add:
```
from selenium.webdriver.firefox.options import Options
options = Options()
options.set_headless(headless=True)
```
Modify the webdriver load line:
`driver = webdriver.Firefox(profile, firefox_options=options)`

If there's a solution for this issue that doesn't involve code changes, please let me know.

https://github.com/algolia/docsearch-scraper/blob/76913d65c6839f95392624a16d0931a8ce93805e/scraper/src/config/browser_handler.py#L25

**Comment by fmarinitrs** [comment]
A workaround to avoid that bug, is using Xvfb and geckodriver. That will avoid the bug keeping all graphical outputs on memory and allowing Javascript execution without the need of the headless mode.

**Comment by s-pace** [comment]
👋 @fmarinitrs.

Sorry for the delays. Thank you for the information.

When you do not use the dockerized version, you will need to install the supported firefox version on your device. So far the scraper is using [firefox v45.0.2](https://www.mozilla.org/en-US/firefox/45.0.2/releasenotes/). Installing this precise version should fix the error you are struggling with.

We are working on fixing such limitation.

**Comment by s-pace** [comment]
The scraper is now relying on ChromeDriver. Closing this issue since it is outdated. Let us know if you need more details.
