### ISSUE TITLE
DocSearch default User-Agent

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch-scraper#404]
It seems that the following websites refuses the crawling from DocSearch with the default User-Agent we use, and we need to masquerade as Googlebot instead (through the use of the `user_agent` key in the config).

- [ ] apache_pulsar
- [ ] datadoghq
- [ ] iost
- [ ] jupiter_cli
- [ ] react-native
- [ ] stripe-docs-v3
- [ ] tabulator
- [ ] yliyun

I don't think we should masquerade as Googlebot in order to do a legitimate crawl. If those websites requested the use of DocSearch but are blocking our crawler, they should find a way to unblock the crawler.

I suggest we:
- [ ] Add the string `DocSearch vXXX` to the User-Agent we send so websites can react accordingly
- [ ] Double-check if we can crawler each of those configs with this new user-agent
- [ ] Manually ask the one that are still blocking us to unblock us

**Comment by pixelastic** [comment]
> It mostly affect Docusaurus implementation.

I'm really surprised by that statement. Most Docusaurus websites are hosted in static platforms like GitHub pages (eg. react-native), and so there is no way the Docusaurus code could react differently to different kind of User-Agent, as this would require to intercept the request in the backend. The backend being GitHub pages, it would mean that all GitHub pages websites would react the same way, which is not the case. Also, I can't find any documentation related to the User-Agent on Docusaurus webpage.

I really don't think our crawling issues are have anything to do with Docusaurus and our User-Agent. 

> Using this user_agent is really relevant in order to have meta data and adapt the rendering based ont it

Could you give an example? I don't see how changing our user-agent will change the metadata we receive?

**Comment by s-pace** [comment]
> I really don't think our crawling issues are have anything to do with Docusaurus and our User-Agent

This is an empirical hypothesis. It definitely worths to dig into this leads. I think that this point is another reason to upgrade to scrapy and python 3.

> Using this user_agent is really relevant in order to have meta data and adapt the rendering based ont it

An example would be to collect some global figures or informations coming from specific metrics like number of views, analytics or any relevant data.

Definitely a good idea to promote our own user_agent. It sounds like it will require some specific changes from the owner's side. Let's be sure that it will not reduce the integration time

**Comment by pixelastic** [comment]
> I think that this point is another reason to upgrade to scrapy and python 3.

Yep, agree. Let's wait until the rewrite for that. We'll need to run a lot of backward compatibility tests to make sure we don't introduce any regression with the rewrite, so we could use that time to also check if changing the UA has any impact on the crawls. In any case, adding the `DocSearch` string to the UA we use will allow owners to react differently on our request if they wish so.

> An example would be to collect some global figures or informations coming from specific metrics like number of views, analytics or any relevant data.

I still don't get it, sorry. Could you give me an example of the kind of metrics you're thinking of? I really don't see how the UA we send to the crawled website will impact our analytics?

**Comment by s-pace** [comment]
> I still don't get it, sorry. Could you give me an example of the kind of metrics you're thinking of? I really don't see how the UA we send to the crawled website will impact our analytics?

I can not find an example and it might be a wrong assumption. I felt like some websites were providing within their DOM some specific metrics in order to give more accurate context (for SEO purposes). We could have use these metrics in order to benefit from this data too.

Definitely agree, let's use it as a good point of improvement for our next iteration over the crawler.

**Comment by pixelastic** [comment]
>  I felt like some websites were providing within their DOM some specific metrics in order to give more accurate context (for SEO purposes).

Oh I see. Yep, I've heard that some websites are sending a trimmed down version of their website to Google when they detect it's crawler by Google bot, in order to have better ranking. I don't think it's mainstream though, and I think we can safely ignore this. One more reason to drop the Googlebot UA :)
