### ISSUE TITLE
Only add facets in Algolia options if there is more than one value

### ISSUE THREAD

**Issue by pixelastic** [algolia/docsearch-scraper#408]
The current snippeter we are using for sending default setup to users is automatically adding facet configuration if some facets are found in the config (which is the case for Docusaurus website by default). This is great and greatly helps users having the correct configuration in their front-end.

In some cases, it creates more output than it should though. For example, a Docusaurus website with only one language (english), will have the snippeter suggesting to add `facetFilters` with a `$LANGUAGE ` value, and saying that the only value is `en`. In that case, it's the same as not specifying anything, so it would be better if the snippeter did not suggest anything.

I had a look at the code, and I think we need to update the loop that goes through all the facets and skip adding them if there is only one possible value. I spent a few minutes trying to do it, but my python foo is too weak to do it with confidence. Happy to pair program on it if needed, but I thought I'd drop that here first.

**Comment by s-pace** [comment]
Definitely something on my TODO. Happy to do it when you are game :)
