### ISSUE TITLE
Assign a unique name to the temporary index

### ISSUE THREAD

**Issue by mojavelinux** [algolia/docsearch-scraper#426]
The docsearch scraper writes records to a temporary index, then moves that index into place once scraping is complete. This is done to avoid impacting the primary index when building the replacement. However, it does not consider the case when more than one instance of the docsearch scraper is running at once (as is sometimes the case in CI).

The temporary index is named by appending "_tmp" to the primary index name. Instead, it should append a unique name (perhaps the timestamp plus a random string). This will prevent the records from docsearch scraper instances from getting mixed up. Of course, the last one to finish will still win, but at least the index will have integrity.

A simple solution, of course, is to prevent more than one instance from running at once. But in certain CI environments, that's simple not possible because jobs get distributed across runners (for example, in GitLab CI).

Another simple solution would be to read the temporary index from an environment variable. In fact, this might be best since the CI job can typically offer up a unique ID based on the job number. Perhaps look for the variable INDEX_NAME_TMP.

**Comment by s-pace** [comment]
👋 @mojavelinux 
Thank you for this nice improvement.

To be honest, this is not a need on our end. Having this `_tmp` suffix is totally fine. Except if you finish the PR #427, we will not put much effort on solving this. Happy to merge this PR though.

**Comment by mojavelinux** [comment]
I just got sidetracked by holiday activity. I plan to wrap up the PR as you requested asap.

**Comment by s-pace** [comment]
Thanks!

**Comment by mojavelinux** [comment]
> To be honest, this is not a need on our end. Having this _tmp suffix is totally fine.

But it's really not fine because if you have two scrapers running at the same time targeting the same index, you're going to end up with corrupted data. And given the fact that a scraper can be triggered by a webhook, there's a very real possibility of this happening. The whole point of the temporary index is to work in a private space, so it really needs to be private (and that means making it configurable).
