### ISSUE TITLE
config_loader.py syntax error in docker image

### ISSUE THREAD

**Issue by Jajcoszek** [algolia/docsearch-scraper#432]
The latest image (from "an hour ago") seems to be built incorrectly. A syntax error is thrown:
```
$ docker run algolia/docsearch-scraper
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/src/index.py", line 8, in <module>
    from .config.config_loader import ConfigLoader
  File "src/config/config_loader.py", line 37
    js_wait = 0doc
                 ^
SyntaxError: invalid syntax
```
The extra `doc` is not in the repository, though.

**Comment by mojavelinux** [comment]
@s-pace @pixelastic Would it be possible to start tagging the Docker images so we can avoid this type of volatility? My builds immediately started failing as well.

**Comment by s-pace** [comment]
Sorry, didn't know it was used by someone else. I just deploy a new image at this exact time.

New image deployed. Should be fine.

**Comment by mojavelinux** [comment]
Thanks @s-pace.

Can I open a new image to add release tags to the Docker image? I'd really like to pin to a specific release so I know what code the CI job is running and it remains stable.

**Comment by s-pace** [comment]
@mojavelinux you can use `algolia/docsearch-scraper:steady` cc @Jajcoszek 

This is just a copy of the current one and it will remain as it.

**Comment by Jajcoszek** [comment]
@s-pace Great. Thank you very much!

**Comment by mojavelinux** [comment]
> you can use algolia/docsearch-scraper:steady

This seems like an odd choice. Why not follow the standard practices of this industry and use actual software tags, like 1.1.0? That way, we know not only that the image is "steady", but which software it's actually using.

I'd be happy to help set this up.

**Comment by s-pace** [comment]
Thank you for sharing this.

The crawler used to add version. Since it is not really clear how it was build we want to start something clearer. We need to do some test and we will enhance the releasing process.

Definitely a good point @mojavelinux, we will make it clearer to understand it asap . Please use `steady` in the meantime.

**Comment by mojavelinux** [comment]
Thank you very much for taking this into consideration. I will monitor this issue and continue to use the steady tag in the meantime.
