### ISSUE TITLE
Different Selectors_key for different sitemap.xml files

### ISSUE THREAD

**Issue by geekyP** [algolia/docsearch-scraper#434]
I need to use one index for different content sources. I have a sitemap file for each source. Also, I need to use different selectors for each source. Is it possible to use Selectors_key with sitemap urls?

Example:
{
  "sitemap_urls": [
    {
      "url": "http://www.example1.com/docs/sitemap.xml",
      "selectors_key": "faq"
    },
    {
      "url": "http://www.example2.com/docs/sitemap.xml",
      "selectors_key": "docs"
    }
  ],
  "selectors": {
    "docs": {
      "lvl0": ".docs h1",
      "lvl1": ".docs h2",
      "lvl2": ".docs h3",
      "lvl3": ".docs h4",
      "lvl4": ".docs h5",
      "text": ".docs p, .docs li"
    },
    "faq": {
      "lvl0": ".faq h1",
      "lvl1": ".faq h2",
      "lvl2": ".faq h3",
      "lvl3": ".faq h4",
      "lvl4": ".faq h5",
      "text": ".faq p, .faq li"
    }
  }
}

**Comment by s-pace** [comment]
Hi @geekyP,

It is not possible to use `selectors_key` with `sitemap_urls`.

`selectors_key` are only suited for `star_urls`. Since the `start_urls` are completely different, you could use the following configuration:

```json
{
  "start_urls": [
    {
      "url": "http://www.example1.com/docs/",
      "selectors_key": "faq"
    },
    {
      "url": "http://www.example2.com/docs/",
      "selectors_key": "docs"
    }
  ],
  "sitemap_urls": [
    "http://www.example1.com/docs/sitemap.xml",
    "http://www.example2.com/docs/sitemap.xml"
  ],
  "selectors": {
    "docs": {
      "lvl0": ".docs h1",
      "lvl1": ".docs h2",
      "lvl2": ".docs h3",
      "lvl3": ".docs h4",
      "lvl4": ".docs h5",
      "text": ".docs p, .docs li"
    },
    "faq": {
      "lvl0": ".faq h1",
      "lvl1": ".faq h2",
      "lvl2": ".faq h3",
      "lvl3": ".faq h4",
      "lvl4": ".faq h5",
      "text": ".faq p, .faq li"
    }
  }
}
```
