### ISSUE TITLE
Using the image from dockerhub

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch-scraper#438]
Hi, 

I found the docsearch image on [Dockerhub](https://hub.docker.com/r/algolia/docsearch-scraper) but I can't figure out how to run the `run` command. 

Here is what I've tried:
`docker run --env-file .env  algolia/docsearch-scraper run config.json`
`docker run --env-file .env  algolia/docsearch-scraper docker:run config.json`

And I get the following message every time:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/src/index.py", line 98, in <module>
    run_config(environ['CONFIG'])
  File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CONFIG'
```
Any idea?

**Comment by s-pace** [comment]
👋 @ArthurFlageul,

You will need to load the config as a variable named `CONFIG` from your .env file and then run:
```sh
docker run -i --env-file .env algolia/docsearch-scraper run
```

You can [see the source here](https://github.com/algolia/docsearch-scraper/blob/master/cli/src/commands/run_config_docker.py#L50) if you need more details regarding the command to run.

Let us know!

**Comment by ArthurFlageul** [comment]
Hi Sylvain, 

Thanks! That works much better 👍  😉 
It would be great to document how to use the image in the dockerhub description 👍

**Comment by s-pace** [comment]
Thank you @ArthurFlageul  You are welcome. Good idea!

Could you share how did you load the configuration into your .env? We would like to promote the most automatised way to do so.

**Comment by ArthurFlageul** [comment]
What I've done for the moment is simply minifying my `conf.json` file and dumping the minified output in the `.env` file to set `CONFIG={"index_name":"myindex","start_urls":[{"url":"http.....`.

In my case, keeping the indented json file separate for easy editing of the indexing is important.

So if you're looking for user-friendly way to do this, maybe a `config_path` parameter could be useful. Then the docker container would take care or adding the conf file to the .env file?

```
docker run -i --env-file .env --conf_path myconf.json algolia/docsearch-scraper
```

**Comment by helfi92** [comment]
I'm using `docker run -it --env-file=env -e "CONFIG=$(cat docsearch.json | jq -r tostring)" algolia/docsearch-scraper`. Having `--conf_path` would definitely be awesome.

**Comment by s-pace** [comment]
Thank you @helfi92 We will document this version then.

Introducing a new parameter can introduce some site effect. We will keep your great feedback for our next iteration.
