### ISSUE TITLE
When `js_render: true` is set; `user_agent` option in the config is not respected

### ISSUE THREAD

**Issue by pranav7** [algolia/docsearch-scraper#455]
When both `js_render: true` and `user_agent: CUSTOM AGENT` are set in the config file, the User Agent option is not respected by `chromedriver`, instead, the default User Agent is sent.

**Comment by s-pace** [comment]
Yes that's true. It is documented too.

Might be an enhancement though

**Comment by pranav7** [comment]
Thank you for taking a look! I have actually created a PR that fixes this: https://github.com/algolia/docsearch-scraper/pull/454 👀
