### ISSUE TITLE
Scraper does not recognize CHROMEDRIVER_PATH when run from Docker image

### ISSUE THREAD

**Issue by joleroi** [algolia/docsearch-scraper#483]
When I try to run the scraper from the Docker image as explained [here](https://community.algolia.com/docsearch/run-your-own.html#run-the-crawl-from-the-docker-image) and [here](https://github.com/algolia/docsearch-scraper/issues/438) I get the following error
```
Exception: Env CHROMEDRIVER_PATH='/usr/local/Caskroom/chromedriver/75.0.3770.140/chromedriver' is not a path to a file
```

The file, however, exists and the scraper runs just fine when running it manually with

```
pipenv shell
./docsearch run <path-to-config>
```

**Comment by s-pace** [comment]
Can you try to use the following image algolia/docsearch-scraper:v1.3.1. I will solve it once I am back from PTO

**Comment by s-pace** [comment]
Closing it since we have not receive any update. A local try on this version works. Feel free to reopen if needed.

**Comment by joleroi** [comment]
Note that this fix only works if no `CHROMEDRIVER_PATH` is given in the `.env` file.

**Comment by s-pace** [comment]
You should not need this env to be set when using the Docker image
