### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by CodeSandwich** [algolia/docsearch-scraper#507]
The [linked documentation](https://docsearch.algolia.com/docs/run-your-own) is out of sync with code in the repository. Following its steps to run the crawler without Docker is impossible, because the commands don't exist anymore.

To be honest I don't think that running a non-dockerized crawler is even possible anymore :thinking:

**Comment by s-pace** [comment]
Could you clarify please? It is possible to run the crawl within docker thanks to `./docsearch docker:run`

**Comment by CodeSandwich** [comment]
It seems that neither `./docsearch run /path/to/your/config.json` nor `./docsearch docker:run` exist anymore. Both of them yield `command not found` error. I'm not surprised, because running `./docsearch --help` doesn't print these commands:

```
Docsearch CLI

Usage:
  ./docsearch command [options] [arguments]

Options:
  --help    Display help message

Available commands:
  bootstrap     Bootstrap a DocSearch config
  test          Run tests
  playground    Launch the playground
 docker
  docker:build  Build scraper images (dev, prod)
```

If I understand correctly, the only way to run a crawler now is to build a docker image and use it. This is fine, but the docs need to reflect that.

**Comment by s-pace** [comment]
Ok so I will fix that but `docker:run` and `run` do work

**Comment by s-pace** [comment]
It does display the full list of available options once you have set up tour environment variables:

```sh
./docsearch --help
Docsearch CLI

Usage:
  ./docsearch command [options] [arguments]

Options:
  --help    Display help message

Available commands:
  bootstrap           Bootstrap a DocSearch config
  test                Run tests
  playground          Launch the playground
  run                 Run a config
  deploy              Deploy a config
 deploy
  deploy:scraper      Deploy docker scraper images
 docker
  docker:build        Build scraper images (dev, prod)
  docker:run          Run a config using docker
 emails
  emails:update       Add or update contact emails
  emails:delete       Delete contact emails
 generate
  generate:email      Generate the email for a docsearch
 invite
  invite:user         Invite to an DocSearch index an email
  invite:remove_user  Uninvite to an DocSearch index an email
```

**Comment by CodeSandwich** [comment]
Wow, I've never seen CLI behavior like this! :exploding_head:

I'm still having this problem though. I've set up `API_KEY` and `APPLICATION_ID` variables, but I'm still getting no `run` or `docker:run`. What variables did you set?

**Comment by s-pace** [comment]
All good then. Happy to help! Do not hesitate to raise issue :)

**Comment by dsmmcken** [comment]
Yeah, I was caught by this too. I am not a python dev, just blindly following the instructions here:
https://docsearch.algolia.com/docs/run-your-own/

I guess I did them a bit out of order. 

Make sure you .env file is populated with your keys before you run pipenv shell, if you modify your .env file you have to restart pipenv shell to load your changes. I mean it makes sense, just pipenv is all new to me.
