### ISSUE TITLE
How to test run a scraper without using up plan?

### ISSUE THREAD

**Issue by CodeSandwich** [algolia/docsearch-scraper#510]
I'm polishing the configuration of the scraper, so I need to do many test runs. Unfortunately every run uploads the results to algolia.net, which uses up operations limit in my plan.

How can I run a test of a scraper without uploading the results (or at least without using up my plan)?

**Comment by s-pace** [comment]
To completely test DocSearch you will have to use Algolia so I definitely recommend to use Algolia.

If you can't, I would recommend to display the records instead of sending them to Algolia. You can edit the scrapper to do so.
