### ISSUE TITLE
How to de-dup pages?

### ISSUE THREAD

**Issue by lorensr** [algolia/docsearch-scraper#550]
When I configure with `"start_urls": ["https://graphql.guide/preface"],`, the scraper picks up `/preface` and `/preface/` as separate pages, and includes them separately in search results. However, they are the same page. How can I de-duplicate them?

```
> docker run -it --env-file=.env.docsearch -e "CONFIG=$(cat docsearch.json | jq -r tostring)" algolia/docsearch-scraper

> DocSearch: https://graphql.guide/preface 10 records)
> DocSearch: https://graphql.guide/preface/ 10 records)
```

**Comment by shortcuts** [comment]
Hi @lorensr,

You can chose to stop the scraper for either of the two patterns.

Using the `stop_urls`, you can add any regex you'd like to use:
stop URLs with a trailing slash
`"stop_urls": ["/$"]`
or without
`"stop_urls": [".*(?<!/)$"]`

Hope this answers your question!
