### ISSUE TITLE
Index updated but results not showing up

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch-scraper#557]
Hi, 

I've been using docsearch happily for a few months but I've noticed today that some pages do not show up in the search, even though the index has been updated.

Example:
[This page](https://docs.talon.one/docs/dev/tutorials/setting-up-strikethrough-pricing) doesn't generate any search results. That page was merged almost exactly 24 hours ago.
The index seems to have been updated 20 minutes ago:
<img width="262" alt="Screenshot 2021-07-20 at 10 34 25" src="https://user-images.githubusercontent.com/28596581/126289285-42bb2d90-89a6-4c94-816e-d1efdda2f6dd.png">

It's a standard Docusaurus V2 site, my config is [here](https://github.com/algolia/docsearch-configs/blob/master/configs/talon.json) and has been fine for months.

What could be causing this behaviour?

**Comment by shortcuts** [comment]
Hey @ArthurFlageul,

This `last update` refers to the Analytics of your index. The last crawl was ~25 hours ago, so the new one will be queued and started ASAP!

I'll keep an eye on the crawl task and let you know

**Comment by ArthurFlageul** [comment]
🤦  I see, thanks. Is there a way to see the date of the last index job in the dashboard?

**Comment by shortcuts** [comment]
Not yet, sorry!

**Comment by ArthurFlageul** [comment]
All good now, sorry for the false alarm! 👍
